// deno-lint-ignore-file no-unused-vars ban-unused-ignore no-explicit-any
import type { ShellSdkContext } from "../../types/sdk.ts"
import type { WorkShift, FinishedWorkShiftInput } from "../../types/types.ts"
import { key } from "../../utils/key.ts"

export type InputType = { input?: FinishedWorkShiftInput }
export type ResponseType = WorkShift[]

const module = async <Input extends InputType, Response extends ResponseType>(
    ctx: ShellSdkContext,
    props: Input,
): Promise<Response> => {
    return await ctx.request(
        "query",
        "finishedWorkShifts",
        [
            "id",
            "comment",
            key("worker", [
                "id",
                "uuid",
                key("group", ["uuid", "title", "user_count", "discount", "created_at"]),
                key("creator", [
                    "id",
                    "uuid",
                    key("group", ["uuid", "title", "user_count", "discount", "created_at"]),
                    "login",
                    "nickname",
                    "phone",
                    "email",
                    "phone_suffix",
                    "dob",
                    "country_code",
                    key("roles", ["id", "alias", "title", "description", "is_service", "priority"]),
                    "first_name",
                    "last_name",
                    "middle_name",
                    "deposit",
                    "bonus",
                    "last_client_activity",
                    "last_worker_activity",
                    key("last_comment", [
                        "id",
                        "entity_id",
                        "text",
                        "created_at",
                        "deleted_at",
                        "data",
                        "request_contact",
                        "request_contact_info",
                        "is_important",
                    ]),
                    "user_discount",
                    "created_at",
                    "updated_at",
                    "disabled_at",
                    "banned_at",
                    "total_hours",
                    key("pausable_sessions", ["id", "duration", "elapsed", "available", "created_at", "expires_at"]),
                    "city",
                    "avatar_url",
                    key("news_consent", ["isGiven", "givenAt", "revokedAt"]),
                    "telegram_link",
                    "discord_link",
                    "steam_link",
                    "vk_link",
                    "is_private",
                    "premium",
                    "unverified",
                    "lead_source",
                    key("discounts", ["value"]),
                    "favorite_club",
                ]),
                "login",
                "nickname",
                "phone",
                "email",
                "phone_suffix",
                "dob",
                "country_code",
                key("roles", [
                    "id",
                    "alias",
                    "title",
                    "description",
                    "is_service",
                    "priority",
                    key("permissions", ["id", "alias", "title", "description"]),
                ]),
                "first_name",
                "last_name",
                "middle_name",
                "deposit",
                "bonus",
                "last_client_activity",
                "last_worker_activity",
                key("last_comment", [
                    "id",
                    "entity_id",
                    "text",
                    key("author", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "created_at",
                    "deleted_at",
                    "data",
                    "request_contact",
                    "request_contact_info",
                    "is_important",
                ]),
                "user_discount",
                "created_at",
                "updated_at",
                "disabled_at",
                "banned_at",
                "total_hours",
                key("pausable_sessions", [
                    "id",
                    key("tariff", [
                        "id",
                        "title",
                        "duration",
                        "use_global_discounts",
                        "has_fixed_finish_time",
                        "created_at",
                        "is_active",
                        "per_minute",
                        "show_in_shell",
                        "show_in_billing",
                        "pausable",
                        "lifetime",
                        "ean",
                        "highlighted",
                        "description",
                        "sort",
                        "is_tracked",
                        "disable_sale_receipt_printing",
                        "online_booking_enabled",
                        "use_on_holidays",
                    ]),
                    "duration",
                    key("host_group", ["id", "title", "created_at", "updated_at"]),
                    "elapsed",
                    "available",
                    "created_at",
                    "expires_at",
                ]),
                "city",
                "avatar_url",
                key("news_consent", ["isGiven", "givenAt", "revokedAt"]),
                "telegram_link",
                "discord_link",
                "steam_link",
                "vk_link",
                "is_private",
                "premium",
                "unverified",
                "lead_source",
                key("discounts", ["value"]),
                "favorite_club",
            ]),
            "created_at",
            "finished_at",
            key("events", ["id", "type", "created_at"]),
            key("money", [
                key("sum", [
                    "cash",
                    "card",
                    "deposit",
                    "bonus",
                    "total",
                    key("currency", ["id", "title", "alias", "letter"]),
                ]),
                "cash_on_start",
            ]),
            key("payments", [
                "id",
                key("client", [
                    "id",
                    "uuid",
                    key("group", ["uuid", "title", "user_count", "discount", "created_at"]),
                    key("creator", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "login",
                    "nickname",
                    "phone",
                    "email",
                    "phone_suffix",
                    "dob",
                    "country_code",
                    key("roles", ["id", "alias", "title", "description", "is_service", "priority"]),
                    "first_name",
                    "last_name",
                    "middle_name",
                    "deposit",
                    "bonus",
                    "last_client_activity",
                    "last_worker_activity",
                    key("last_comment", [
                        "id",
                        "entity_id",
                        "text",
                        "created_at",
                        "deleted_at",
                        "data",
                        "request_contact",
                        "request_contact_info",
                        "is_important",
                    ]),
                    "user_discount",
                    "created_at",
                    "updated_at",
                    "disabled_at",
                    "banned_at",
                    "total_hours",
                    key("pausable_sessions", ["id", "duration", "elapsed", "available", "created_at", "expires_at"]),
                    "city",
                    "avatar_url",
                    key("news_consent", ["isGiven", "givenAt", "revokedAt"]),
                    "telegram_link",
                    "discord_link",
                    "steam_link",
                    "vk_link",
                    "is_private",
                    "premium",
                    "unverified",
                    "lead_source",
                    key("discounts", ["value"]),
                    "favorite_club",
                ]),
                key("client_session", [
                    "id",
                    key("client", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    key("hosts", ["id", "started_at", "finished_at"]),
                    "duration",
                    "elapsed",
                    key("payment", [
                        "id",
                        "sum",
                        "bonus",
                        "created_at",
                        "is_refunded",
                        "not_refundable",
                        "card_sum",
                        "cash_sum",
                        "comment",
                        "cashback",
                    ]),
                    "postpaid",
                    "total_cost",
                    key("seances", [
                        "id",
                        "duration",
                        "elapsed",
                        "created_at",
                        "started_at",
                        "finished_at",
                        "cancelled_at",
                    ]),
                    "created_at",
                    "started_at",
                    "finished_at",
                    "canceled_at",
                    "time_left",
                ]),
                key("work_shift", [
                    "id",
                    "comment",
                    key("worker", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "created_at",
                    "finished_at",
                    key("events", ["id", "type", "created_at"]),
                    key("money", ["cash_on_start"]),
                    key("payments", [
                        "id",
                        "sum",
                        "bonus",
                        "created_at",
                        "is_refunded",
                        "not_refundable",
                        "card_sum",
                        "cash_sum",
                        "comment",
                        "cashback",
                    ]),
                    key("cashOrders", ["id", "sum", "comment", "created_at"]),
                ]),
                key("promo_code", [
                    "id",
                    key("author", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    key("client", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "code",
                    "value",
                    "amount",
                    "entity_id",
                    "created_at",
                    "is_tracked",
                ]),
                key("discount", [
                    "id",
                    key("author", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    key("client", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "title",
                    "value",
                    "entity_id",
                    "created_at",
                    "is_tracked",
                ]),
                "sum",
                "bonus",
                "created_at",
                key("items", ["id", "payment_id", "combo_id", "amount", "sum"]),
                "is_refunded",
                "not_refundable",
                "card_sum",
                "cash_sum",
                "comment",
                "cashback",
                key("external_data", ["external_id", "external_method"]),
            ]),
            key("cashOrders", [
                "id",
                key("work_shift", [
                    "id",
                    "comment",
                    key("worker", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "created_at",
                    "finished_at",
                    key("events", ["id", "type", "created_at"]),
                    key("money", ["cash_on_start"]),
                    key("payments", [
                        "id",
                        "sum",
                        "bonus",
                        "created_at",
                        "is_refunded",
                        "not_refundable",
                        "card_sum",
                        "cash_sum",
                        "comment",
                        "cashback",
                    ]),
                    key("cashOrders", ["id", "sum", "comment", "created_at"]),
                ]),
                "sum",
                "comment",
                "created_at",
            ]),
        ],
        { ...(props as any) },
    )
}

export default module<InputType, ResponseType>
