// deno-lint-ignore-file no-unused-vars ban-unused-ignore no-explicit-any
import type { ShellSdkContext, ShellSdkPaginatorInput } from "../../types/sdk.ts"
import type { EventPaginated, MobileEventsInput } from "../../types/types.ts"
import { key } from "../../utils/key.ts"

export type InputType = { paginator?: ShellSdkPaginatorInput; input?: MobileEventsInput }
export type ResponseType = EventPaginated

const module = async <Input extends InputType["input"], Response extends ResponseType>(
    ctx: ShellSdkContext,
    props: Input,
    paginator?: ShellSdkPaginatorInput,
): Promise<Response> => {
    return await ctx.request(
        "query",
        "mobileEvents",
        [
            key("data", [
                "id",
                "type",
                "created_at",
                "relations",
                key("workShift", [
                    "id",
                    "comment",
                    key("worker", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "created_at",
                    "finished_at",
                    key("events", ["id", "type", "created_at"]),
                    key("money", ["cash_on_start"]),
                    key("payments", [
                        "id",
                        "sum",
                        "bonus",
                        "created_at",
                        "is_refunded",
                        "not_refundable",
                        "card_sum",
                        "cash_sum",
                        "comment",
                        "cashback",
                    ]),
                    key("cashOrders", ["id", "sum", "comment", "created_at"]),
                ]),
                key("initiator", [
                    "id",
                    "uuid",
                    key("group", ["uuid", "title", "user_count", "discount", "created_at"]),
                    key("creator", [
                        "id",
                        "uuid",
                        "login",
                        "nickname",
                        "phone",
                        "email",
                        "phone_suffix",
                        "dob",
                        "country_code",
                        "first_name",
                        "last_name",
                        "middle_name",
                        "deposit",
                        "bonus",
                        "last_client_activity",
                        "last_worker_activity",
                        "user_discount",
                        "created_at",
                        "updated_at",
                        "disabled_at",
                        "banned_at",
                        "total_hours",
                        "city",
                        "avatar_url",
                        "telegram_link",
                        "discord_link",
                        "steam_link",
                        "vk_link",
                        "is_private",
                        "premium",
                        "unverified",
                        "lead_source",
                        "favorite_club",
                    ]),
                    "login",
                    "nickname",
                    "phone",
                    "email",
                    "phone_suffix",
                    "dob",
                    "country_code",
                    key("roles", ["id", "alias", "title", "description", "is_service", "priority"]),
                    "first_name",
                    "last_name",
                    "middle_name",
                    "deposit",
                    "bonus",
                    "last_client_activity",
                    "last_worker_activity",
                    key("last_comment", [
                        "id",
                        "entity_id",
                        "text",
                        "created_at",
                        "deleted_at",
                        "data",
                        "request_contact",
                        "request_contact_info",
                        "is_important",
                    ]),
                    "user_discount",
                    "created_at",
                    "updated_at",
                    "disabled_at",
                    "banned_at",
                    "total_hours",
                    key("pausable_sessions", ["id", "duration", "elapsed", "available", "created_at", "expires_at"]),
                    "city",
                    "avatar_url",
                    key("news_consent", ["isGiven", "givenAt", "revokedAt"]),
                    "telegram_link",
                    "discord_link",
                    "steam_link",
                    "vk_link",
                    "is_private",
                    "premium",
                    "unverified",
                    "lead_source",
                    key("discounts", ["value"]),
                    "favorite_club",
                ]),
                key("initiatorHost", [
                    "id",
                    "group_id",
                    key("group", ["id", "title", "created_at", "updated_at", "priority"]),
                    "type_id",
                    "position",
                    "alias",
                    "comment",
                    "mac_addr",
                    "ip_addr",
                    "dns_name",
                    "coord_x",
                    "coord_y",
                    "is_deleted",
                    "in_service",
                    "created_at",
                    key("info", ["processor", "ram", "video", "disc", "shell_version"]),
                    key("counters", ["cpu_temp", "disk_temp", "active_window"]),
                    key("sessions", ["id", "host_id", "company_id", "alias", "started_at", "finished_at"]),
                    key("client_sessions", [
                        "id",
                        "duration",
                        "elapsed",
                        "postpaid",
                        "total_cost",
                        "created_at",
                        "started_at",
                        "finished_at",
                        "canceled_at",
                        "time_left",
                    ]),
                    "last_online",
                    "online",
                    key("bookings", ["id", "hosts", "from", "to", "comment", "startsIn", "group", "byClient"]),
                    "device_has_changed",
                    "device_updated_at",
                    key("device_changes", ["alias", "old", "new"]),
                    "locked",
                    "admin_called_at",
                    "online_booking_enabled",
                ]),
                "description",
            ]),
        ],
        { input: props },
        paginator || { page: 1 },
    )
}

export default module<InputType["input"], ResponseType>
